#pragma once

#define DEBUG_MATRIX_SCAN_RATE

// Split hand
#undef SPLIT_USB_DETECT

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

// Trackball enable / config
#define PMW33XX_CS_PIN GP17
// #define POINTING_DEVICE_MOTION_PIN GP21
#define POINTING_DEVICE_COMBINED
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_TASK_THROTTLE_MS 1
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_X_RIGHT

// Tap hold config
#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT // Fix for mod tap rollover

// Used for program reset combo
#define COMBO_COUNT 2
